# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flut',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
