# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_twitterclone', '0005_auto_20160520_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flut',
            name='user_author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flutter_twitterclone.User'),
        ),
    ]
